<?php
/**
 * Veritrans VT Web Model Standard
 *
 * @category   Mage
 * @package    vtweb/form.phtml
 * @author     cby
 * this template is rendered when Veritrans payment method is chosen. This is description about Veritrans Payment Method
 */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    
<li><h2>Informations:</h2></li>
<li>Payment can be made through all ATMs that have logo: Prima/ATM Bersama/Alto.</li>
<li>Please do payment soon, the Virtual Account Number will expire in 24 hours.</li>
<li>Minimum transaction using Mandiri ATM is Rp 50.000.</li>
<li>Order details will be sent via email.</li>
    
    
    
</ul>